In [ ]:
import numpy as np
num_user=10
num_movies=5
rating_data=np.random.randint(0,2,size=(num_user,num_movies))
rating_data.shape

(10, 5)

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
num_hidden_units=3
weights=np.random.normal(0,0.1,(num_movies,num_hidden_units))
print(weights.shape)
print(weights)

(5, 3)
[[-0.06479467  0.10074499  0.01150905]
 [-0.11423366  0.05133611  0.0532215 ]
 [-0.00545507  0.14306909 -0.04360882]
 [ 0.04290605 -0.2031122  -0.24806607]
 [ 0.05320075 -0.11867598 -0.07490627]]


In [ ]:
visible_bias=np.zeros(num_movies)
print(visible_bias.shape)
hidden_bias=np.zeros(num_hidden_units)
learning_rate=0.1
print(hidden_bias.shape)

(5,)
(3,)


In [ ]:
num_epochs = 1000
for epoch in range(num_epochs):
   for user_ratings in rating_data:
    # Positive phase
    hidden_probabilities =sigmoid(np.dot(user_ratings, weights) + hidden_bias)
    positive_associations = np.outer(user_ratings, hidden_probabilities)
    # Reconstruction
    visible_probabilities =sigmoid(np.dot(hidden_probabilities, weights.T) + visible_bias)
   # Negative phase
   hidden_probabilities_recon=sigmoid (np.dot (visible_probabilities, weights) + hidden_bias )
   negative_associations = np.outer(visible_probabilities, hidden_probabilities_recon)
   #update weight
   weights += learning_rate * (positive_associations - negative_associations)
   visible_bias += learning_rate * (user_ratings - visible_probabilities)
   hidden_bias += learning_rate * (hidden_probabilities - hidden_probabilities_recon)

In [ ]:
user_id = 5
user_ratings =rating_data[user_id]
hidden_probabilities=sigmoid(np.dot(user_ratings, weights) + hidden_bias)
visible_probabilities =sigmoid (np.dot(hidden_probabilities, weights.T) + visible_bias)
predicted_ratings = visible_probabilities
print("Predicted ratings for user", user_id, ":", predicted_ratings)


Predicted ratings for user 5 : [0.00280775 0.99743956 0.00280744 0.99741759 0.99742911]


In [ ]:
max_rating = np.max(predicted_ratings)
max_index = np.argmax(predicted_ratings)
print("The maximum predicted rating for user", user_id, "is", max_rating, "at movie", max_index)


The maximum predicted rating for user 5 is 0.9974395595106861 at movie 1
